#' A coefficient analysis 
#' 
#' Object of class \code{Coefficient} are created by the \code{coefAnalysis} functions
#'
#' 
#' An object of the class `Coefficient' has the following slots:
#' \itemize{
#' \item \code{coef} A matrix of coefficients generated by all variable combinations
#' \item \code{Rsquare} A vector of R-square values from the regressions
#' \item \code{MeanRsquare} A vector of the mean of R-square values from the regressions
#' \item \code{x} The first input: A matrix of covariates
#' \item \code{y} The second input: A numeric vector length of the number of regressions using variable combinations 
#' }
#'
#' @author Elif Ozdemir: \email{eozdemir@wustl.edu}
#' @aliases Coefficient-class initialize,Coefficient-method getCoefficient,Coefficient-method 
#' @rdname Coefficient
#' @export
setClass(Class="Coefficient",
         contains="Regression",
         slots = list(
           coef = "matrix",
           Rsquare = "numeric",
           MeanRsquare="numeric",
           x = "matrix",
           y = "numeric"
         ),
         prototype = prototype(
           coef = matrix(),
           Rsquare = numeric(),
           MeanRsquare=numeric(),
           x = matrix(),
           y = numeric()
         )
)

#' @export
setMethod("initialize", "Coefficient", 
          function(.Object, coef=matrix(0), Rsquare=numeric(0), MeanRsquare=numeric(0), x=matrix(0), y=numeric(0)){
            .Object@coef<- coef
            .Object@Rsquare<- Rsquare
            .Object@MeanRsquare<- MeanRsquare
            .Object@x<- x
            .Object@y<- y
            return(.Object)
          }
) 

#' @rdname Coefficient
#' @export 
setGeneric("getCoefficient",
           function(object="Coefficient"){
             standardGeneric("getCoefficient")
           }
)

#' @export
setMethod("getCoefficient", "Coefficient",
          function(object){ 
            return(list(MeanRsquare=object@MeanRsquare))
          }
)

#' @export
setMethod("getRegression", "Regression",
          function(object){
            return(list(coef=object@coef,Rsquare=object@Rsquare))
          }
)