#' A regression analysis 
#' 
#' Object of class \code{Regression} are created by the \code{regAnalysis} functions
#'
#' 
#' An object of the class `Regression' has the following slots:
#' \itemize{
#' \item \code{coef} A matrix of coefficients generated by all variable combinations
#' \item \code{Rsquare} A vector of R-square values from the regressions
#' \item \code{x} The first input: A matrix of covariates
#' \item \code{y} The second input: A numeric vector length of the number of regressions using variable combinations 
#' }
#'
#' @author Elif Ozdemir: \email{eozdemir@wustl.edu}
#' @aliases Regression-class initialize,Regression-method getRegression,Regression-method 
#' @rdname Regression
#' @export
setClass(Class="Regression", 
     slots = list(
          coef = "matrix",
          Rsquare = "numeric",
          x = "matrix",
          y = "numeric"
          ),
     prototype = prototype(
          coef = matrix(),
          Rsquare = numeric(),
          x = matrix(),
          y = numeric()
          )
     )

#' @export
setMethod("initialize", "Regression", 
         function(.Object, coef=matrix(0), Rsquare=numeric(0), x=matrix(0), y=numeric(0)){
         .Object@coef<- coef
         .Object@Rsquare<- Rsquare
         .Object@x<- x
         .Object@y<- y
         return(.Object)
         }
         ) 

#' @rdname Regression
#' @export 
setGeneric("getRegression",
       function(object="Regression"){
       standardGeneric("getRegression")
       }
       )

#' @export
setMethod("getRegression", "Regression",
        function(object){ 
        return(list(coef=object@coef,Rsquare=object@Rsquare))
        }
        )
